linters:
  enable-all: true
  disable:
    # Disable deprecated linters.
    - exportloopref
    - gomnd
    - execinquery
    # Disable impractical linters.
    - depguard
    - exhaustruct

linters-settings:
  tagliatelle:
    case:
      rules:
        # We can't influence this as these are provided by ModemManager.
        json: kebab
